#!/bin/bash

# Admin Reset Quick Reference Guide
# ==================================

echo "=== Balrmarket Admin Management ==="
echo ""
echo "Available Commands:"
echo ""
echo "1. RESET EVERYTHING (recommended for fresh start):"
echo "   ts-node manage-admins.ts reset ~/.config/solana/id.json [admin-pubkeys...]"
echo ""
echo "2. View current admin state:"
echo "   ts-node manage-admins.ts info"
echo ""
echo "3. Close admin hierarchy (clears all admins):"
echo "   ts-node manage-admins.ts close ~/.config/solana/id.json <receiver-pubkey>"
echo ""
echo "4. Initialize new admin hierarchy:"
echo "   ts-node manage-admins.ts init ~/.config/solana/id.json"
echo ""
echo "5. Add super admins:"
echo "   ts-node manage-admins.ts add ~/.config/solana/id.json <pubkey1> [pubkey2] [pubkey3]..."
echo ""
echo "=== Quick Start ==="
echo ""
echo "To completely reset and add new admins:"
echo "  1. anchor build && anchor deploy"
echo "  2. ts-node manage-admins.ts reset ~/.config/solana/id.json <admin1> <admin2> <admin3>"
echo ""
echo "=== System Changes ==="
echo "  • Regular admins removed - only super admins now"
echo "  • Max super admins increased from 3 to 10"
echo "  • All operations require super admin privileges"
echo "  • New close_admin_hierarchy instruction to clear all admins"
echo ""
